import React, { useState, useEffect } from 'react';
import { Map } from 'lucide-react';
import Last30Days from './components/Last30Days';
import Restoration from './components/Restoration';
import NeighborWatch from './components/NeighborWatch';

function App() {
  const [activeTab, setActiveTab] = useState('Last 30 Days');
  const [data, setData] = useState({ feed: [], timeline: [], neighborWatch: [] });

  useEffect(() => {
    // Fetch static data generated by our local cron job
    fetch('/data.json')
      .then(res => res.json())
      .then(fetchedData => setData(fetchedData))
      .catch(err => console.error('Error fetching static data:', err));
  }, []);

  const renderContent = () => {
    switch (activeTab) {
      case 'Last 30 Days':
        return <Last30Days feed={data.feed} />;
      case 'Restoration':
        return <Restoration timeline={data.timeline} />;
      case 'Neighbor Watch':
        return <NeighborWatch neighborWatch={data.neighborWatch} />;
      default:
        return <Last30Days feed={data.feed} />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-100 font-sans text-slate-800 antialiased relative">
      <div className="max-w-5xl mx-auto p-4 sm:p-6 lg:p-8">
        
        {/* Header */}
        <header className="flex justify-between items-center mb-8">
          <div className="flex items-center gap-4">
            <div className="bg-blue-600 text-white p-3 rounded-2xl shadow-lg shadow-blue-500/30">
              <Map size={32} strokeWidth={2} />
            </div>
            <div>
              <h1 className="text-3xl font-extrabold tracking-tight">
                Randall Preserve <span className="text-blue-600">Watch</span>
              </h1>
              <p className="text-sm font-semibold tracking-wider text-slate-400 uppercase mt-1">
                Daily Intelligence Dashboard
              </p>
            </div>
          </div>
        </header>

        {/* Navigation Tabs */}
        <nav className="flex items-center justify-between bg-slate-200/50 p-2 rounded-2xl mb-8 backdrop-blur-sm border border-white">
          {['Last 30 Days', 'Restoration', 'Neighbor Watch'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`flex-1 py-3 px-4 text-center text-sm font-bold rounded-xl transition-all ${
                activeTab === tab 
                  ? 'bg-white shadow-sm text-blue-600 border border-slate-100 ring-1 ring-slate-900/5' 
                  : 'text-slate-500 hover:text-slate-700 hover:bg-white/40'
              }`}
            >
              {tab}
            </button>
          ))}
        </nav>

        {/* Main Content Area */}
        <main className="min-h-[600px] mb-12 animate-in fade-in duration-300">
          {renderContent()}
        </main>

        <footer className="text-center text-xs text-slate-400 font-medium pb-8 border-t border-slate-200 pt-8 mt-12">
          <p>© {new Date().getFullYear()} RANDALL PRESERVE WATCH</p>
          <p className="mt-1">AUTOMATED DAILY INTELLIGENCE</p>
        </footer>
      </div>
    </div>
  );
}

export default App;
