import React, { useState, useEffect } from 'react';
import { Map } from 'lucide-react';
import Last30Days from './components/Last30Days';
import Restoration from './components/Restoration';
import NeighborWatch from './components/NeighborWatch';

function App() {
  const [activeTab, setActiveTab] = useState('Last 30 Days');
  const [data, setData] = useState({ feed: [], timeline: [], neighborWatch: [] });

  useEffect(() => {
    // Fetch static data generated by our local cron job
    const dataUrl = `${import.meta.env.BASE_URL}data.json`;
    fetch(dataUrl)
      .then(res => res.json())
      .then(fetchedData => setData(fetchedData))
      .catch(err => console.error(`Error fetching static data from ${dataUrl}:`, err));
  }, []);

  const renderContent = () => {
    switch (activeTab) {
      case 'Last 30 Days':
        return <Last30Days feed={data.feed} />;
      case 'Restoration':
        return <Restoration timeline={data.timeline} />;
      case 'Neighbor Watch':
        return <NeighborWatch neighborWatch={data.neighborWatch} />;
      default:
        return <Last30Days feed={data.feed} />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-800 antialiased relative overflow-hidden">
      
      {/* Dynamic Glassmorphism Background Orbs */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
        <div className="absolute -top-[10%] -left-[10%] w-[50%] h-[50%] rounded-full bg-emerald-400/20 blur-[120px] mix-blend-multiply opacity-70 animate-pulse"></div>
        <div className="absolute top-[20%] -right-[10%] w-[40%] h-[60%] rounded-full bg-sky-400/20 blur-[120px] mix-blend-multiply opacity-60"></div>
        <div className="absolute -bottom-[10%] left-[20%] w-[60%] h-[40%] rounded-full bg-teal-300/20 blur-[120px] mix-blend-multiply opacity-50"></div>
      </div>

      <div className="max-w-5xl mx-auto p-4 sm:p-6 lg:p-8 relative z-10">
        
        {/* Header */}
        <header className="flex justify-between items-center mb-10 mt-4">
          <div className="flex items-center gap-5">
            <div className="bg-gradient-to-tr from-blue-600 to-emerald-500 text-white p-3.5 rounded-2xl shadow-xl shadow-blue-500/20 ring-1 ring-white/50">
              <Map size={32} strokeWidth={2.5} />
            </div>
            <div>
              <h1 className="text-3xl font-display font-extrabold tracking-tight text-slate-900 drop-shadow-sm">
                Randall Preserve <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-emerald-500">Watch</span>
              </h1>
              <p className="text-sm font-semibold tracking-wider text-slate-500 uppercase mt-1">
                Daily Intelligence Dashboard
              </p>
            </div>
          </div>
        </header>

        {/* Navigation Tabs */}
        <nav className="flex items-center justify-between bg-white/40 p-2 rounded-2xl mb-10 backdrop-blur-xl border border-white/60 shadow-sm ring-1 ring-slate-900/5">
          {['Last 30 Days', 'Restoration', 'Neighbor Watch'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`flex-1 py-3 px-4 text-center text-sm font-bold rounded-xl transition-all duration-300 ${
                activeTab === tab 
                  ? 'bg-white shadow-[0_2px_10px_rgba(0,0,0,0.06)] text-blue-600 border border-white/80 ring-1 ring-slate-900/5 transform scale-[1.02]' 
                  : 'text-slate-500 hover:text-slate-800 hover:bg-white/50'
              }`}
            >
              {tab}
            </button>
          ))}
        </nav>

        {/* Main Content Area */}
        <main className="min-h-[600px] mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
          {renderContent()}
        </main>

        <footer className="text-center text-xs text-slate-400 font-medium pb-8 border-t border-slate-200/50 pt-8 mt-12 backdrop-blur-sm">
          <p>© {new Date().getFullYear()} RANDALL PRESERVE WATCH</p>
          <p className="mt-1">AUTOMATED DAILY INTELLIGENCE</p>
        </footer>
      </div>
    </div>
  );
}

export default App;
